#!/usr/bin/env node
var program     = require('commander');
var fs          = require('fs');
var clone       = require("nodegit").Repo.clone;
var handlebars  = require('handlebars');
var path        = require('path');
var Fiber       = require('fibers');
var Future      = require('fibers/future');
var clc         = require('cli-color');

// helpers
var Logs = {
  'log': function(message){
    console.log(message);
  },
  'info': function(message){
    console.log(clc.green(message));
  },
  'warn': function(message){
    console.log(clc.yellow(message));
  },
  'error': function(message){
    console.log(clc.red(message));
  }
};

function deleteFolderRecursive (path) {
  if( fs.existsSync(path) ) {
    fs.readdirSync(path).forEach(function(file,index){
      var curPath = path + "/" + file;
      if(fs.lstatSync(curPath).isDirectory()) { // recurse
        deleteFolderRecursive(curPath);
      } else { // delete file
        fs.unlinkSync(curPath);
      }
    });
    fs.rmdirSync(path);
  }
};

function isMeteorAppDir () {
  var cpath = __dirname,
  appPath = path.resolve(cpath, '.meteor');
  if (!fs.existsSync(appPath))
    throw new Error('not found meteor app');
};

// commands
program
  .version('0.1.0')

program
  .command('init')
  .description('download project and save locally [stable]')
  .action(function(){
  try {
    var rootPath = __dirname,
    templatePath = path.resolve(rootPath, 'template');
    if (fs.existsSync(templatePath)) {
      // delete
      Logs.info('delete folder ...');
      deleteFolderRecursive(templatePath);
    }
    // update
    Logs.info('create folder ...');
    fs.mkdirSync(templatePath, 0777);

    // Clone a given repository into a specific folder.
    Logs.info('clone git ...');
    clone("https://github.com/particle4dev/sample-project.git", templatePath, null, function(err, repo) {
      if (err) {
        throw err;
      }
      Logs.info('done !');
    });
  }
  catch(err){
    Logs.error('init: ' + err.message);
  }
});

program
  .command('generate [name]')
  .description('create meteor project [stable]')
  .action(function(name){
    
});

program
  .command('meteormobile [name]')
  .description('create meteor mobile project')
  .action(function(name){

});

program
  .command('collection [name] [where]')
  .description('add meteor collection ')
  .action(function(name, where){
  try {
    console.log(name, where);
    isMeteorAppDir();
  }
  catch(err){
    Logs.error('collection: ' + err.message);
  }
});

program
  .command('*')
  .action(function(env){
    console.log('Enter a Valid command');
    terminate(true);
});

program.parse(process.argv);

// var source = "<p>Hello, my name is {{name}}. I am from {{hometown}}. I have " +
//          "{{kids.length}} kids:</p>" +
//          "<ul>{{#kids}}<li>{{name}} is {{age}}</li>{{/kids}}</ul>";
// var template = handlebars.compile(source);

// var data = { "name": "Alan", "hometown": "Somewhere, TX",
//          "kids": [{"name": "Jimmy", "age": "12"}, {"name": "Sally", "age": "4"}]};
// var result = template(data);
// console.log(result);
